name: Deploy to ECR 

on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set timezone to Toronto
      run: |
        sudo ln -fs /usr/share/zoneinfo/America/Toronto /etc/localtime
        echo "Current datetime: $(date)"

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr_assignment1_repo
        
        IMAGE_TAG: $(date +"%Y%m%d%H%M%S")
        echo "IMAGE_TAG: $IMAGE_TAG"
        
        APP_COLOR_CONTAINER1: "blue"
        APP_COLOR_CONTAINER2: "pink"
        APP_COLOR_CONTAINER3: "lime"
      run: |
        cd app/
        ls -ltra
        
        #docker build mysql
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}" -f Dockerfile_mysql .
        echo "Mysql build complete"

        #push docker image to registory
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}"
        echo "Mysql push to ecr complete"

        # run mysql container
        docker run -d --name mysql_db -e MYSQL_ROOT_PASSWORD=pw $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}"
        docker ps
        echo "Sleep for 10s then... Showing list of databases in MYSQL:"
        sleep 10
        docker exec mysql_db mysql -ppw -e "show databases;"
        echo "Mysql container complete"

        #export variables
        export DBHOST=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my_db`
        export DBPORT=3306
        export DBUSER=root
        export DATABASE=employees
        export DBPWD=pw
        export APP_COLOR=blue
        
        # Docker build app
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}" .
        echo "App build complete"

        #Docjer container app push to ecr
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}"
        echo "push done"
        
        # Unit test
        docker run -d -p 8080:8080  -e DBHOST=$DBHOST \
          -e DBPORT=$DBPORT -e  DBUSER=$DBUSER \
          -e DBPWD=$DBPWD $ECR_REGISTRY/$ECR_REPOSITORY
        echo "App 0 container run complete"

        - >
          docker run -d -p 8081:8080 --name app_container1 \
            -e DBHOST=$DBHOST_CONTAINER1 \
            -e APP_COLOR=$APP_COLOR_CONTAINER1 \
            $ECR_REGISTRY/$ECR_REPOSITORY
            
          echo "App 1 container run complete"
          
          docker run -d -p 8082:8080 --name app_container2 \
            -e DBHOST=$DBHOST_CONTAINER2 \
            -e APP_COLOR=$APP_COLOR_CONTAINER2 \
            $ECR_REGISTRY/$ECR_REPOSITORY
            
          echo "App 2 container run complete"
  
          docker run -d -p 8083:8080 --name app_container3 \
            -e DBHOST=$DBHOST_CONTAINER3 \
            -e APP_COLOR=$APP_COLOR_CONTAINER3 \
            $ECR_REGISTRY/$ECR_REPOSITORY
            
          echo "App 3 container run complete"
        echo "Public IP below:"
        curl ifconfig.me
        wget -qO- ifconfig.me

        echo "Before docker ps"
        docker ps
        echo "All done now"
       
